language: cpp

dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      compiler: clang
      env: DISTRO=ubuntu DISTRO_VERSION=16.04
    - os: linux
      compiler: clang
      env: CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug" \
           DISTRO=ubuntu DISTRO_VERSION=17.10 \
    - os: linux
      compiler: clang
      env: CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug" \
           DISTRO=fedora DISTRO_VERSION=27
    - os: linux
      compiler: clang
      env: DISTRO=fedora DISTRO_VERSION=27
    - os: linux
      compiler: gcc
      env: CMAKE_FLAGS="-DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug" \
           BUILD_EXTRA=COVERAGE DISTRO=ubuntu DISTRO_VERSION=16.04
    - os: linux
      compiler: gcc
      env: DISTRO=ubuntu DISTRO_VERSION=17.10
    - os: linux
      compiler: gcc
      env: DISTRO=fedora DISTRO_VERSION=27

script:
  - ci/build-linux.sh

after_success:
  - ci/upload-coverage.sh

# Cache the (saved) docker images.
# With recent version of docker one can reuse a prior image as a
# source cache, that can speed up the builds, as the dependencies and
# images can be reused ...
# TODO() - we need to add a cron job to rebuild without a cache every
# so often, the dependencies do change and we want to validate that
# the examples build with the newer versions.  That is easy to do with
# a cron-based build in Travis that cleans up the cache every X days.
cache:
  directories:
    - docker-images/ubuntu/16.04
    - docker-images/ubuntu/17.10
    - docker-images/fedora/27

install:
  - ci/install-linux.sh

before_cache:
  - ci/cache-linux.sh

notifications:
  email: false
